#                          Technology and LEF layer map
# Design "picosoc"
#
# Technology and LEF layers are mapped automatically by innovus.
# If a user needs customised mapping, specify a layermap file. Layermap file
# is specified using command "setExtractRCMode -lefTechFileMap <layermapFile>".
#

# Mapping of layers are from <lefLayer> to <techLayer>

extraction_setup \
	-enable_eco_mode true \
	-technology_layer_map \
		poly         poly \
		mcon         mcon \
		met1         metal1 \
		via          via1 \
		met2         metal2 \
		via2         via2 \
		met3         metal3 \
		via3         via3 \
		met4         metal4 \
		via4         via4 \
		met5         metal5 \


# Technology File: "/pnr_training/WORK_BATCH1/saif_39/final_project/FINAL_PROJECT/pnr/DESIGN/route_finalf.inn.dat/libs/mmmc/rctypical/qrcTechFile"

#
# This file was generated by Innovus v22.18-s118_1 on Wed Aug 12 11:44:05 2026

