tclmode

# Generated by Genus(TM) Synthesis Solution 21.18-s082_1, revision 1.568
# Generated on: Tue Aug 11 17:56:23 +06 2026 (Tue Aug 11 11:56:23 UTC 2026)

set_screen_display -noprogress
set_dofile_abort exit

### Alias mapping flow is enabled. ###
# Root attribute 'alias_flow'                 was 'true'.

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

# Turns on the flowgraph datapath solver.
set wlec_analyze_dp_flowgraph true
# Indicates that resource sharing datapath optimization is present.
set share_dp_analysis         true

# The flowgraph solver is recommended for datapath analysis in LEC 19.1 or newer.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required &&
    $wlec_analyze_dp_flowgraph} {
    set DATAPATH_SOLVER_OPTION "-flowgraph"
} elseif {$share_dp_analysis} {
    set DATAPATH_SOLVER_OPTION "-share"
} else {
    set DATAPATH_SOLVER_OPTION ""
}

tcl_set_command_name_echo on

set logfile logs/intermediate2final.lec.log ;# user can modify this name for succeeding runs

set_log_file $logfile -replace

usage -auto -elapse

set_mapping_method -sensitive

set_verification_information fv_map_optv_db

read_implementation_information fv/picosoc -golden fv_map -revised optv

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 1,4 -norelease_license
set_compare_options -threads 1,4

set env(RC_VERSION)     "21.18-s082_1"
set env(CDN_SYNTH_ROOT) "/tools/cadence/GENUS211/tools.lnx86"
set CDN_SYNTH_ROOT      "/tools/cadence/GENUS211/tools.lnx86"
set env(CW_DIR) "/tools/cadence/GENUS211/tools.lnx86/lib/chipware"
set CW_DIR      "/tools/cadence/GENUS211/tools.lnx86/lib/chipware"
set lec_version_required "21.20249"
if { ($lec_version < $lec_version_required) &&
    [file exists /tools/cadence/GENUS211/tools.lnx86/lib/chipware/old_encrypt_sim]} {
    set env(CW_DIR_SIM) "/tools/cadence/GENUS211/tools.lnx86/lib/chipware/old_encrypt_sim"
    set CW_DIR_SIM      "/tools/cadence/GENUS211/tools.lnx86/lib/chipware/old_encrypt_sim"
} else {
    set env(CW_DIR_SIM) "/tools/cadence/GENUS211/tools.lnx86/lib/chipware/sim"
    set CW_DIR_SIM      "/tools/cadence/GENUS211/tools.lnx86/lib/chipware/sim"
}
set_multiplier_implementation boothrca -both

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_notranslate_modules -library -both sky130_sram_2kbyte_1rw1r_32x512_8 sky130_sram_4kbyte_1rw1r_32x1024_8
# ILM modules: 

add_search_path . /tools/cadence/GENUS211/tools.lnx86/lib/tech -library -both
read_library -liberty -both \
    /pdk/sky130_scl_9T_0.1.2/sky130_scl_9T_HS/lib/sky130_tt_1.8_25_nldm.lib.gz \
    /pdk/sky130_scl_9T_0.1.2/sky130_scl_9T_LP/lib/sky130_tt_1.8_25_nldm.lib.gz \
    /pdk/sky130_scl_9T_0.1.2/sky130_scl_9T_tech/lib/sky130_scl_9T_phyCells.lib \
    /pnr_training/WORK_BATCH1/saif_39/final_project/FINAL_PROJECT/ram/sky130_sram_2kbyte/lib/sky130_sram_2kbyte_1rw1r_32x512_8_TT_1p8V_25C.lib \
    /pnr_training/WORK_BATCH1/saif_39/final_project/FINAL_PROJECT/ram/sky130_sram_4kbyte/lib/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.lib

read_design -verilog95   -golden -lastmod -noelab fv/picosoc/fv_map.v.gz
elaborate_design -golden -root {picosoc}

read_design -verilog95   -revised -lastmod -noelab outputs/opt.v
elaborate_design -revised -root {picosoc}

#add_name_alias fv/picosoc/fv_map.singlebit.original_name.alias.json.gz -golden
#set_mapping_method -alias -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

#add_name_alias fv/picosoc/optv.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff dlat -both

# Reports the quality of the implementation information.
# This command is only available with LEC 20.10-p100 or later.
set lec_version_required "20.10100"
if {$lec_version >= $lec_version_required} {
    check_verification_information
}

set_analyze_option -auto -report_map

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_compared_points noneq.compared_points.picosoc.fv_map.optv.tcl -class noneq -tclmode -replace
set lec_version_required "21.10100"
if {$lec_version >= $lec_version_required} {
    analyze_nonequivalent -source_diagnosis
    report_nonequivalent_analysis > noneq.source_diag.picosoc.fv_map.optv.rpt
}
report_test_vector -noneq > noneq.test_vector.picosoc.fv_map.optv.rpt
write_verification_information
report_verification_information

# Reports how effective the implementation information was.
# This command is only available with LEC 18.20-d330 or later.
set lec_version_required "18.20330"
if {$lec_version >= $lec_version_required} {
    report_implementation_information
}

puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}

# Generate a detailed summary of the run.
# This command is available with LEC 19.10-p100 or later.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required} {
    analyze_results -logfiles $logfile
}

vpxmode

exit -f
